VEX_DIR=/home/bh2010/bitblaze/vine-ibinhunt/valgrind/VEX
LIBASMIR_CXXFLAGS=-I/home/bh2010/bitblaze/vine-ibinhunt/valgrind/VEX/pub -I/home/bh2010/bitblaze/vine-ibinhunt/src/include -g -O2
LIBASMIR_LDFLAGS=-L/home/bh2010/bitblaze/vine-ibinhunt/valgrind/VEX -L/home/bh2010/bitblaze/vine-ibinhunt/src 
LIBASMIR_LIBS=-lasmir -lvex -lbfd -liberty
